<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131004001104 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE mrimann_como_domain_model_aggregateddataperuser (persistence_object_identifier VARCHAR(40) NOT NULL, useremail VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, month VARCHAR(255) NOT NULL, commitcount INT NOT NULL, commitcountbugfix INT NOT NULL, commitcountfeature INT NOT NULL, commitcountdocumentation INT NOT NULL, commitcounttask INT NOT NULL, commitcounttest INT NOT NULL, commitcountrelease INT NOT NULL, commitcountunknown INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE mrimann_como_domain_model_award (persistence_object_identifier VARCHAR(40) NOT NULL, type VARCHAR(255) NOT NULL, month VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, useremail VARCHAR(255) NOT NULL, commitcount INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE mrimann_como_domain_model_commit (persistence_object_identifier VARCHAR(40) NOT NULL, repository VARCHAR(40) DEFAULT NULL, hash VARCHAR(255) NOT NULL, commitline VARCHAR(255) NOT NULL, authorname VARCHAR(255) NOT NULL, authoremail VARCHAR(255) NOT NULL, committername VARCHAR(255) NOT NULL, committeremail VARCHAR(255) NOT NULL, date DATETIME NOT NULL, commitclass VARCHAR(255) NOT NULL, isaggregated TINYINT(1) NOT NULL, INDEX IDX_FAA3FE4F5CFE57CD (repository), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE mrimann_como_domain_model_repository (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, lastprocessedcommit VARCHAR(255) NOT NULL, isactive TINYINT(1) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE mrimann_como_domain_model_commit ADD CONSTRAINT FK_FAA3FE4F5CFE57CD FOREIGN KEY (repository) REFERENCES mrimann_como_domain_model_repository (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE mrimann_como_domain_model_commit DROP FOREIGN KEY FK_FAA3FE4F5CFE57CD");
		$this->addSql("DROP TABLE mrimann_como_domain_model_aggregateddataperuser");
		$this->addSql("DROP TABLE mrimann_como_domain_model_award");
		$this->addSql("DROP TABLE mrimann_como_domain_model_commit");
		$this->addSql("DROP TABLE mrimann_como_domain_model_repository");
	}
}

?>