#                                                                                  #
# Default subroutes configuration for the Mrimann.CoMo package                     #
#                                                                                  #

-
  name: 'foo'
  uriPattern: 'mrimann.como/{@controller}(/{@action})'
  defaults:
    '@controller': 'Standard'
    '@action':     'index'
  appendExceedingArguments: true

-
  name: 'bar'
  uriPattern: 'mrimann.como'
  defaults:
    '@controller': 'Standard'
    '@action':     'index'

