Mrimann:
  CoMo:
    cacheBasePath: %FLOW_PATH_DATA%Temporary/

    # defines the amount of days that will be extracted from the git log
    # as it wouldn't make sense to fetch e.g. the last 10 years and spend
    # tons of resources on extracting and aggregating - and then just
    # electing last month's awards
    # defaults to 100 days - which is roughly 3 months
    maxDaysToFetchFromGitLogHistory: 100

    # whether to send mails to the ceremony master upon election of a new
    # coder of the month
    sendNotificationMailsForCoderOfTheMonth: FALSE

    # whether to send mails to the ceremony master upon election of a new
    # topic award winner
    sendNotificationMailsForTopicAwardWinner: FALSE

    # the e-mail address of the ceremony master (get's notifications
    # upon newly elected awards)
    ceremonyMasterEmail: mario+como@rimann.org

    # e-mail and name of the sender of all the notification mails
    senderEmail: como@example.org
    senderName: CoMo